[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "postgresql", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "python --version",
  "python -m pip --version", 
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt --no-cache-dir"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python run.py"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
